version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para o host
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: